### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ghost** [asurbernardo/amperage#29]
# 1. Comment widget
> https://comments.app/

# 2.  Search widget
> https://www.algolia.com/

# 3. amp-auto-ads
```
<script async custom-element="amp-auto-ads"
        src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>
```

```
<amp-auto-ads type="adsense"
        data-ad-client="ca-pub-idxxxxx">
</amp-auto-ads>

```

**Comment by asurcodes** [comment]
Hello @LGTMXD, I have already considered all of these ideas and I will answer your requests in order:

1. This blog already supports a comment widgets, actually it's widget agnostic, so you could theoretically use any comment system you want and use an iframe to include it on your web site, that is waht I do on my own site (https://asur.dev/en/amperage/theme-kitchen-sink/), you can check the README to read the example I provide for Disqus, everything is public.

2. Algolia might not be the best solution because it would require some sort of sync step to update their indexes at the time of deploy, on the other hand GoHugo custom output formats look more promising (https://gohugo.io/templates/output-formats/) but this is tricky to implement in AMP, specially at the UI level. Consider this one a maybe.

3. This is the most subjective of all 3, I prefer being able to set ads for myself instead of getting it automatically, this would be nice to have as a configuration `[manual|auto]` but this would require some time. This however is the most viable.

Thank you for your ideas and stay tuned for more features. OFC pull requests are always welcome! :smiley:
